<a href="https://colab.research.google.com/github/rajkiran15/colab-hands-on/blob/main/mnist_digit_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from PIL import Image
import os

# --------------- Load and Prepare Data --------------- #
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Take 1 image from x_train (first row of 60000)
one_image_vector = x_train[0]   # shape → (784,) but part of 2-D dataset
one_image_2d     = one_image_vector.reshape(28, 28)  # convert to 2-D image

# Convert to real image format (0–255)
img = Image.fromarray((one_image_2d * 255).astype(np.uint8))

# save that image
img.save("sample_1.jpg")

print("Training Input Dataset", x_train)
print("\nTraining Output Dataset", y_train)

# Normalize + reshape to vector of 784
x_train = x_train.reshape(-1, 784) / 255.0
x_test  = x_test.reshape(-1, 784) / 255.0

print("Normalize Training Input Dataset", x_train)
print("\nNormalize Testing Input Dataset", x_test)

# --------------- Build Model --------------- #
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(784,)),
    layers.Dropout(0.2),
    layers.Dense(10, activation='softmax')
])

# --------------- Compile & Train --------------- #
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("\nTraining model...")
model.fit(x_train, y_train, epochs=5, validation_split=0.2)

# --------------- Test Accuracy --------------- #
print("\nEvaluating on test data...")
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"\n🔥 Test Accuracy: {test_acc * 100:.2f}%")

# --------------- Predict on 5 new samples from test set --------------- #
print("\nPredicting first 5 test images...")
preds = model.predict(x_test[:5])

for i, p in enumerate(preds):
    print(f"Image {i+1} → Predicted Digit:", p.argmax())

# --------------- Predict on 1 custom image from folder --------------- #
def predict_custom_image(img_path):
    # Load image and convert to grayscale
    img = Image.open(img_path).convert("L")

    # Resize only if not 28x28
    if img.size != (28, 28):
      img = img.resize((28, 28))

    img_array = np.array(img)

    # Flatten → normalize → reshape for model input
    img_array = img_array.reshape(1, 784) / 255.0

    pred = model.predict(img_array)
    return pred.argmax()

# Set your custom image path here
custom_folder = "digits"  # folder name
custom_image  = "digit_1.png"  # image file name
custom_path   = os.path.join(custom_folder, custom_image)

if os.path.exists(custom_path):
    result = predict_custom_image(custom_path)
    print("\n🖼 Custom Image Prediction:", result)
else:
    print("\n⚠ No custom image found at:", custom_path)


Training Input Dataset [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]

Training Output Dataset [5 0 4 ... 5 6 8]
Normalize Training Input Dataset [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8394 - loss: 0.5427 - val_accuracy: 0.9549 - val_loss: 0.1587
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9508 - loss: 0.1652 - val_accuracy: 0.9658 - val_loss: 0.1187
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9643 - loss: 0.1197 - val_accuracy: 0.9688 - val_loss: 0.1011
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9696 - loss: 0.0947 - val_accuracy: 0.9724 - val_loss: 0.0912
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9743 - loss: 0.0815 - val_accuracy: 0.9739 - val_loss: 0.0867

Evaluating on test data...
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9703 - loss: 0.0922

🔥 Test Accuracy: 97.50%

Predicting first 5 test images...


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Image 1 → Predicted Digit: 7
Image 2 → Predicted Digit: 2
Image 3 → Predicted Digit: 1
Image 4 → Predicted Digit: 0
Image 5 → Predicted Digit: 4

⚠ No custom image found at: digits/digit_1.png
